services:
  ollama:
    image: ollama/ollama
    container_name: ollama-container
    ports:
      - "11434:11434"
    networks:
      - shared-network

  model-puller:
    image: docker
    container_name: model-puller
    depends_on:
      - ollama
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shared-network
    entrypoint: ["sh", "-c", "
      docker exec ollama-container ollama pull bge-m3 &&
      echo 'bge-m3 completed' &&
      docker exec ollama-container ollama pull nomic-embed-text && 
      echo 'nomic-embed-text completed' &&  
      docker exec ollama-container ollama pull llama3 &&
      echo 'llama3 completed'
    "]

networks:
  shared-network:
    driver: bridge
